In [109]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [110]:
# Raw Data
df = pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [111]:
# Labeling
label_sex = {
    'male': 1,
    'female': 0
}

label_smoker ={
    'yes' : 1,
    'no' : 0
}

label_region ={
    'northwest' : 0,
    'southwest' : 1,
    'southeast' : 2,
    'northeast' : 3 
}

df['sex'] = df['sex'].map(label_sex)
df['smoker'] = df['smoker'].map(label_smoker)
df['region'] = df['region'].map(label_region)


# Data After Labeling 
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

In [112]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

#Dataset
X = df[['age', 'bmi', 'region','sex', 'smoker', 'children']]
  
# VIF DF
data_vif = pd.DataFrame()
data_vif["feature"] = X.columns
  
# Calculating VIF DF
data_vif["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]
  
print(data_vif)

    feature       VIF
0       age  7.588734
1       bmi  9.938670
2    region  2.789478
3       sex  2.002652
4    smoker  1.261195
5  children  1.799980

In [113]:
# Dropping Column
df = df.drop(df.columns[0], axis=1)
df = df.drop(df.columns[1], axis=1)
df.head()

   sex  children  smoker  region      charges
0    0         0       1       1  16884.92400
1    1         1       0       2   1725.55230
2    1         3       0       2   4449.46200
3    1         0       0       0  21984.47061
4    1         0       0       0   3866.85520

In [114]:
# Data After Processing

new_data = df
new_data.head()

   sex  children  smoker  region      charges
0    0         0       1       1  16884.92400
1    1         1       0       2   1725.55230
2    1         3       0       2   4449.46200
3    1         0       0       0  21984.47061
4    1         0       0       0   3866.85520

In [115]:
# Regressing
X = new_data.iloc[:, :-1].values
y = new_data.iloc[:, 4].values

In [126]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [131]:
y = y.reshape(len(y), 1)
# Check Shape
y.shape

(1338, 1)

In [135]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [138]:
# Mixing
gabung = np.concatenate((y_test, y_pred))
gabung

array([[ 3227.1211    ],
       [36307.7983    ],
       [ 7371.772     ],
       [ 8125.7845    ],
       [14571.8908    ],
       [ 7077.1894    ],
       [13607.36875   ],
       [20149.3229    ],
       [ 9630.397     ],
       [21098.55405   ],
       [40419.0191    ],
       [ 4686.3887    ],
       [13555.0049    ],
       [ 8835.26495   ],
       [10806.839     ],
       [ 4433.9159    ],
       [ 4399.731     ],
       [46255.1125    ],
       [25382.297     ],
       [ 6799.458     ],
       [10928.849     ],
       [ 2154.361     ],
       [ 6272.4772    ],
       [38709.176     ],
       [11163.568     ],
       [17178.6824    ],
       [33471.97189   ],
       [ 1131.5066    ],
       [ 4751.07      ],
       [10577.087     ],
       [19798.05455   ],
       [10156.7832    ],
       [21677.28345   ],
       [43578.9394    ],
       [13747.87235   ],
       [ 2196.4732    ],
       [11674.13      ],
       [ 7954.517     ],
       [21232.18226   ],
       [27941.28758   ],
       [ 7624.63      ],
       [10825.2537    ],
       [18963.17192   ],
       [17878.90068   ],
       [ 2150.469     ],
       [32108.66282   ],
       [ 2741.948     ],
       [18310.742     ],
       [ 5261.46945   ],
       [ 8988.15875   ],
       [27000.98473   ],
       [16232.847     ],
       [ 6358.77645   ],
       [10796.35025   ],
       [ 7537.1639    ],
       [ 1708.92575   ],
       [ 6653.7886    ],
       [ 5002.7827    ],
       [ 7345.084     ],
       [13725.47184   ],
       [ 2020.177     ],
       [ 1253.936     ],
       [ 3736.4647    ],
       [12574.049     ],
       [23288.9284    ],
       [ 2904.088     ],
       [12523.6048    ],
       [ 2483.736     ],
       [ 8527.532     ],
       [21195.818     ],
       [13126.67745   ],
       [ 4296.2712    ],
       [ 6664.68595   ],
       [ 7151.092     ],
       [ 2775.19215   ],
       [ 9644.2525    ],
       [11150.78      ],
       [ 6571.02435   ],
       [ 9304.7019    ],
       [ 3591.48      ],
       [24059.68019   ],
       [21659.9301    ],
       [42983.4585    ],
       [ 2974.126     ],
       [52590.82939   ],
       [34672.1472    ],
       [ 2137.6536    ],
       [ 6775.961     ],
       [ 9778.3472    ],
       [21774.32215   ],
       [39611.7577    ],
       [10594.2257    ],
       [25517.11363   ],
       [19673.33573   ],
       [ 3366.6697    ],
       [ 4438.2634    ],
       [16420.49455   ],
       [ 3471.4096    ],
       [18157.876     ],
       [ 6112.35295   ],
       [ 7050.0213    ],
       [41097.16175   ],
       [14319.031     ],
       [ 4463.2051    ],
       [ 6666.243     ],
       [51194.55914   ],
       [11411.685     ],
       [12032.326     ],
       [12430.95335   ],
       [ 3766.8838    ],
       [ 1719.4363    ],
       [ 2117.33885   ],
       [ 8283.6807    ],
       [32548.3405    ],
       [ 5245.2269    ],
       [ 8457.818     ],
       [43921.1837    ],
       [ 7144.86265   ],
       [ 1634.5734    ],
       [13352.0998    ],
       [ 2045.68525   ],
       [ 1149.3959    ],
       [ 9748.9106    ],
       [13393.756     ],
       [16884.924     ],
       [17904.52705   ],
       [12363.547     ],
       [ 3279.86855   ],
       [12096.6512    ],
       [ 1121.8739    ],
       [11554.2236    ],
       [45710.20785   ],
       [19361.9988    ],
       [ 4391.652     ],
       [ 1615.7667    ],
       [10579.711     ],
       [12269.68865   ],
       [11538.421     ],
       [14394.5579    ],
       [ 9875.6804    ],
       [38511.6283    ],
       [ 6334.34355   ],
       [ 7153.5539    ],
       [58571.07448   ],
       [11881.358     ],
       [ 4350.5144    ],
       [24869.8368    ],
       [18767.7377    ],
       [ 3704.3545    ],
       [ 2789.0574    ],
       [ 5974.3847    ],
       [ 1141.4451    ],
       [13919.8229    ],
       [ 6435.6237    ],
       [14426.07385   ],
       [ 2007.945     ],
       [14394.39815   ],
       [13063.883     ],
       [13129.60345   ],
       [ 6986.697     ],
       [14256.1928    ],
       [34779.615     ],
       [ 8233.0975    ],
       [ 4058.1161    ],
       [11833.7823    ],
       [ 6837.3687    ],
       [ 3238.4357    ],
       [ 3558.62025   ],
       [24915.04626   ],
       [ 7243.8136    ],
       [ 6940.90985   ],
       [ 8539.671     ],
       [ 8428.0693    ],
       [ 1261.442     ],
       [ 9855.1314    ],
       [ 7201.70085   ],
       [ 3490.5491    ],
       [ 4134.08245   ],
       [34439.8559    ],
       [13430.265     ],
       [ 1146.7966    ],
       [ 4827.90495   ],
       [ 2585.85065   ],
       [ 5729.0053    ],
       [ 9182.17      ],
       [42856.838     ],
       [ 1631.8212    ],
       [37165.1638    ],
       [10141.1362    ],
       [ 3021.80915   ],
       [ 3757.8448    ],
       [ 1725.5523    ],
       [ 7147.105     ],
       [ 9715.841     ],
       [19594.80965   ],
       [ 9788.8659    ],
       [ 1628.4709    ],
       [25656.57526   ],
       [ 1625.43375   ],
       [ 6184.2994    ],
       [ 9193.8385    ],
       [ 5966.8874    ],
       [ 2850.68375   ],
       [12646.207     ],
       [ 2217.46915   ],
       [19040.876     ],
       [40103.89      ],
       [14474.675     ],
       [ 1977.815     ],
       [ 5428.7277    ],
       [13937.6665    ],
       [12592.5345    ],
       [13204.28565   ],
       [11856.4115    ],
       [33307.5508    ],
       [ 6113.23105   ],
       [39836.519     ],
       [41676.0811    ],
       [ 2801.2588    ],
       [11879.10405   ],
       [ 3857.75925   ],
       [ 3925.7582    ],
       [42969.8527    ],
       [ 1906.35825   ],
       [ 1769.53165   ],
       [ 3943.5954    ],
       [47462.894     ],
       [ 2680.9493    ],
       [ 4357.04365   ],
       [ 7045.499     ],
       [ 4076.497     ],
       [ 5152.134     ],
       [30063.58055   ],
       [ 5253.524     ],
       [16796.41194   ],
       [48885.13561   ],
       [ 6289.7549    ],
       [ 2026.9741    ],
       [10118.424     ],
       [ 2102.2647    ],
       [ 2719.27975   ],
       [ 2211.13075   ],
       [ 7345.7266    ],
       [ 4529.477     ],
       [ 6360.9936    ],
       [12146.971     ],
       [20773.62775   ],
       [ 1622.1885    ],
       [ 3176.8159    ],
       [12648.7034    ],
       [ 6593.5083    ],
       [ 7935.29115   ],
       [37133.8982    ],
       [24535.69855   ],
       [ 7512.267     ],
       [45702.02235   ],
       [20745.9891    ],
       [ 1674.6323    ],
       [14451.83515   ],
       [ 2690.1138    ],
       [11566.30055   ],
       [ 7046.7222    ],
       [30166.61817   ],
       [ 6652.5288    ],
       [13224.693     ],
       [10106.13425   ],
       [ 2352.96845   ],
       [36189.1017    ],
       [ 8517.37848875],
       [31450.53379761],
       [ 8939.15539174],
       [ 7875.75175917],
       [31670.3836242 ],
       [ 8741.57336149],
       [ 9387.54513723],
       [31674.72867035],
       [ 8943.50043789],
       [32294.08760359],
       [31446.18875145],
       [ 9167.69531064],
       [ 8099.94663192],
       [ 7427.36201369],
       [ 8939.15539174],
       [ 8719.30556515],
       [ 7875.75175917],
       [33608.29895139],
       [33164.25425206],
       [11329.80551058],
       [ 8517.37848875],
       [ 7647.21184027],
       [ 8521.72353491],
       [32096.50557334],
       [ 8939.15539174],
       [32320.70044609],
       [ 8714.96051899],
       [ 7875.75175917],
       [ 8297.52866216],
       [ 7651.55688643],
       [32962.32717566],
       [ 8714.96051899],
       [31643.7707817 ],
       [30997.79900597],
       [31674.72867035],
       [ 8095.60158576],
       [ 8293.18361601],
       [ 9585.12716747],
       [ 7651.55688643],
       [ 9589.47221363],
       [ 8293.18361601],
       [ 8073.33378942],
       [ 8521.72353491],
       [ 8095.60158576],
       [ 7647.21184027],
       [ 9391.89018338],
       [ 8095.60158576],
       [31002.14405212],
       [ 8719.30556515],
       [ 7423.01696753],
       [ 8521.72353491],
       [31226.33892487],
       [ 7427.36201369],
       [ 8099.94663192],
       [ 9360.93229472],
       [ 8099.94663192],
       [11105.61063783],
       [ 8517.37848875],
       [ 7647.21184027],
       [ 8741.57336149],
       [ 7647.21184027],
       [ 7651.55688643],
       [ 7423.01696753],
       [ 7651.55688643],
       [ 8741.57336149],
       [ 8297.52866216],
       [ 7427.36201369],
       [ 7875.75175917],
       [ 9163.35026448],
       [31450.53379761],
       [ 7647.21184027],
       [ 9360.93229472],
       [ 8073.33378942],
       [ 9585.12716747],
       [ 8073.33378942],
       [ 7423.01696753],
       [ 8939.15539174],
       [ 7423.01696753],
       [ 9167.69531064],
       [ 9589.47221363],
       [ 8714.96051899],
       [33608.29895139],
       [30997.79900597],
       [ 7647.21184027],
       [31226.33892487],
       [31450.53379761],
       [ 7875.75175917],
       [ 8293.18361601],
       [ 8741.57336149],
       [30997.79900597],
       [31450.53379761],
       [ 7875.75175917],
       [ 8745.91840765],
       [ 7427.36201369],
       [ 7871.40671302],
       [ 9391.89018338],
       [32935.71433316],
       [ 8521.72353491],
       [ 8719.30556515],
       [ 8068.98874326],
       [ 8095.60158576],
       [31674.72867035],
       [ 7647.21184027],
       [ 9167.69531064],
       [10881.41576509],
       [31872.3107006 ],
       [ 9585.12716747],
       [ 8293.18361601],
       [ 8095.60158576],
       [ 8517.37848875],
       [ 8521.72353491],
       [ 7423.01696753],
       [ 7871.40671302],
       [31450.53379761],
       [ 8517.37848875],
       [ 7651.55688643],
       [31002.14405212],
       [ 9387.54513723],
       [ 7871.40671302],
       [ 7427.36201369],
       [ 7427.36201369],
       [ 7875.75175917],
       [ 8521.72353491],
       [ 7651.55688643],
       [31221.99387871],
       [31674.72867035],
       [ 9589.47221363],
       [ 9391.89018338],
       [ 9387.54513723],
       [ 7875.75175917],
       [ 8521.72353491],
       [31674.72867035],
       [33388.44912481],
       [ 9585.12716747],
       [ 7871.40671302],
       [ 8517.37848875],
       [ 8714.96051899],
       [ 8939.15539174],
       [ 8099.94663192],
       [ 8095.60158576],
       [32962.32717566],
       [10033.51691296],
       [ 8068.98874326],
       [32316.35539993],
       [ 8939.15539174],
       [ 8517.37848875],
       [33612.64399755],
       [32742.47734907],
       [ 7875.75175917],
       [ 8073.33378942],
       [ 8517.37848875],
       [ 7875.75175917],
       [ 9813.66708637],
       [ 9813.66708637],
       [ 8714.96051899],
       [ 7647.21184027],
       [10679.48868869],
       [ 7647.21184027],
       [ 8099.94663192],
       [ 8719.30556515],
       [ 7423.01696753],
       [31226.33892487],
       [ 8517.37848875],
       [ 9167.69531064],
       [ 7871.40671302],
       [ 8099.94663192],
       [ 8517.37848875],
       [ 8095.60158576],
       [ 9387.54513723],
       [10455.29381594],
       [ 8073.33378942],
       [ 8293.18361601],
       [ 8073.33378942],
       [ 7651.55688643],
       [ 8517.37848875],
       [ 8714.96051899],
       [ 8745.91840765],
       [ 7423.01696753],
       [31446.18875145],
       [10033.51691296],
       [ 7875.75175917],
       [10037.86195911],
       [ 8095.60158576],
       [ 8719.30556515],
       [ 8293.18361601],
       [32518.28247633],
       [ 7871.40671302],
       [32096.50557334],
       [10037.86195911],
       [ 7423.01696753],
       [ 7871.40671302],
       [ 8521.72353491],
       [ 7651.55688643],
       [ 9387.54513723],
       [32316.35539993],
       [11105.61063783],
       [ 7427.36201369],
       [ 8095.60158576],
       [ 7427.36201369],
       [ 9809.32204021],
       [ 8714.96051899],
       [ 7875.75175917],
       [ 7423.01696753],
       [ 8939.15539174],
       [ 8095.60158576],
       [31872.3107006 ],
       [32518.28247633],
       [ 8517.37848875],
       [ 7651.55688643],
       [10037.86195911],
       [ 8073.33378942],
       [11101.26559168],
       [ 8095.60158576],
       [ 7871.40671302],
       [30997.79900597],
       [10033.51691296],
       [32513.93743017],
       [31450.53379761],
       [ 9163.35026448],
       [ 8741.57336149],
       [ 8099.94663192],
       [ 9387.54513723],
       [32092.16052719],
       [ 7427.36201369],
       [ 7427.36201369],
       [ 8095.60158576],
       [32742.47734907],
       [ 7427.36201369],
       [ 7423.01696753],
       [ 8293.18361601],
       [ 8297.52866216],
       [ 8939.15539174],
       [ 9365.27734088],
       [ 9589.47221363],
       [ 8741.57336149],
       [31446.18875145],
       [ 8521.72353491],
       [ 7871.40671302],
       [ 8939.15539174],
       [ 8099.94663192],
       [ 8068.98874326],
       [ 8095.60158576],
       [ 8517.37848875],
       [ 8939.15539174],
       [ 9360.93229472],
       [ 7651.55688643],
       [32320.70044609],
       [ 7871.40671302],
       [ 7423.01696753],
       [ 7871.40671302],
       [ 9167.69531064],
       [ 8095.60158576],
       [31446.18875145],
       [32289.74255743],
       [10235.44398936],
       [32294.08760359],
       [32940.05937932],
       [ 7875.75175917],
       [ 8095.60158576],
       [ 7423.01696753],
       [ 8099.94663192],
       [ 8517.37848875],
       [ 8073.33378942],
       [ 9813.66708637],
       [ 8293.18361601],
       [ 8741.57336149],
       [ 7427.36201369],
       [33612.64399755]])

In [141]:
# Get R2 Score
r2_lr = r2_score(y_test, y_pred)
print(r2_lr)

0.5990868652569482